 export const  ADDEXPENSE="ADDEXPENSE";

 export const REMOVE_EXPENSES="REMOVE_EXPENSES";

 export const EDIT_EXPENSES="EDIT_EXPENSES";

 export const FILTER_EXPENSES_BY_NAME="FILTER_EXPENSES_BY_NAME";
 export const SORT_BY_DATE="SORT_BY_DATE";
 export const SORT_BY_AMOUNT="SORT_BY_AMOUNT";

 export const SORT_BY_ENDDATE="SORT_BY_ENDDATE";

 export const SORT_BY_STARTDATE="SORT_BY_STARTDATE";

 export const VISIBLE_DATA="VISIBLE_DATA";

 export const SEARCH_BY_AMOUNT="SEARCH_BY_AMOUNT"